### PR TITLE
Admin edit delete

### PR DESCRIPTION
**Pull request by LuWang1983**
Backend: I implemented the isAdminMiddleware for access control.
Frontend: I implemented remove btn and am still working on edit/toggle.

Doc: I updated the README file to display on our gitHub Homepage, feel free to take a look and add anything you want.

### CODE REVIEW

**Review by sarajculhane — CHANGES_REQUESTED** [review]
Looks great but as with the other PR, just confirm that you have QA'd login / signup because of naming convention change

**Comment by LuWang1983** [comment]
Hey Sara, if you are talking about the login/Signup you implemented, no I didn't QA. The reason for the change is because now users.js in redux store only deals with fetchAllUsers, add, delete and update while auth.js deals with authentication. So users no longer can fetch any user whenever they can, rather, when the current user is an Admin, he/she can view/edit the users/singleUser, if the current user is not an admin, he/she cannot view/edit users. But feel free to let me know if there's other ways to incorporate this without breaking anything.

**Comment by sarajculhane** [comment]
Got it... I don't think that this change will impact it, but I think it would be good if you could do a login and sign up to confirm that they are still working before we merge to master since some of the same files were edited.  Just want to avoid regressions.

**Comment by LuWang1983** [comment]
Yeah sure! Just to confirm, I git stash my current branch to save them. Go back to master, pull and merge my changes with the current master version, then test right?

**Comment by LuWang1983** [comment]
nvm, figured it out. Git versions have been confusing for me.

**Comment by LuWang1983** [comment]
I think the auth part is fine actually but ran into this when I npm run start-dev
not sure if you got it as well

Screen Shot 2020-08-07 at 1 43 55 PM

**Comment by sarajculhane** [comment]
Ok. I am not getting that but that's also the piece I have been working on since yesterday.  Haven't done a PR because I'm not 100% done.  Getting closer though. I guess I can do a PR so that the error is resolved?

**Comment by LuWang1983** [comment]
I just fixed export default in product-update and it worked, minor bug

**Comment by sarajculhane** [comment]
Yeah I remembering fixing that bug.  Might be a small merge conflict once I submit my PR later but no big deal. Merging this.

**Review by sarajculhane — APPROVED** [review]

**Pull request merged**
